### ISSUE TITLE
Playbook not working unless inventory file is named

### ISSUE THREAD

**Issue by PatrickSteiner** [ivanthelad/ansible-azure#23]
ansible-playbook -i bla ....

**Comment by ivanthelad** [comment]
This only occurs inside the Docker implementation for somereason. I also discovered it doesn'T work work when -i uses a full path  "ansible-playbook - /mypath/inventory ... "

**Comment by ivanthelad** [comment]
the docker install.sh file has been update to resolve this issue. See docker/install.sh
