### ISSUE TITLE
Add support to Premium storage

### ISSUE THREAD

**Issue by tahonen** [ivanthelad/ansible-azure#28]
If vm type is *DS* something vm support premium storage (Premium_LRS). Currently only possibility is Standard_LRS.

**Comment by ivanthelad** [comment]
Added support. Premium storage now configurable on each node from the ansible config file by passing a variable called storagetype, see here for example 
https://github.com/ivanthelad/ansible-azure/blob/master/all_examples/all_mega_cluster#L94

  master3:
    name: master3
    datadisksize: 80
    machinesize: Standard_DS3_v2
    storagtype: Premium_LRS
    tags:
      region: "{{ region }}"
      zone: infra
      type: infra

improvement contained in 
https://github.com/ivanthelad/ansible-azure/commit/8d1e313c9cddd7848b2f7487e8f13a33644c76c8
https://github.com/ivanthelad/ansible-azure/commit/ae58c52dcef57ee605b6c05a3f021a215e3463f5
