### ISSUE TITLE
Variable to define size for jumphost and different and also infra and appnodes

### ISSUE THREAD

**Issue by tahonen** [ivanthelad/ansible-azure#30]
Something like this

master_vmSize: Standard_DS1_v2
node_vmSize: Standard_DS1_v2 
infranode_vmSize: Standard_DS1_v2
jumphost_vmSize: Standard_DS1_v2

**Comment by ivanthelad** [comment]
Cool, been meaning to do this

**Comment by ivanthelad** [comment]
Done, configurable via the variable "machinesize" on each node

  master3:
    name: master3
    datadisksize: 80
    machinesize: Standard_DS3_v2
    storagtype: Premium_LRS
    tags:
      region: "{{ region }}"
      zone: infra
      type: infra
