### ISSUE TITLE
dockerfile issue 

### ISSUE THREAD

**Issue by dwojciec** [ivanthelad/ansible-azure#35]
http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm doesn't exist 
you have to replace it with 
http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm

**Comment by ivanthelad** [comment]
done
